### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by ab5tract**

### CODE REVIEW

**Review by antononcube — COMMENTED** [review]
The suggested change has to be made in the CLI file "./bin/jupyter-chatbook.raku" --
see the variable `$spec`.

Then we run this command in order the new kernel spec to take effect:

```
jupyter-chatbook.raku --generate-config --force
```

After that running the chatbook with:

```
jupyter console --kernel=raku
```

gives the error:

> FileNotFoundError: [Errno 2] No such file or directory: '--repl-mode=process'

**Comment by ab5tract** [comment]
It wasn't clear to me whether the generator or this file took precedence. Out of curiosity, why do they both exist?

I'll have to look into how jupyter console passes arguments, as the output you have shared doesn't make any sense if the arguments are being passed to the raku binary.

**Comment by antononcube** [comment]
> It wasn't clear to me whether the generator or this file took precedence. Out of curiosity, why do they both exist?

I "inherited" that setup from ["Jupyter::Kernel"](https://github.com/bduggan/raku-jupyter-kernel). I assume both are present for documentation and/or reference purposes.

**Comment by ab5tract** [comment]
So IIUC, the previous setup was relying on the shebang line in `bin/jupyter-chatbook.raku` to launch the interpreter.

One resolution is presented here in this PR.

The other is to add `--repl-mode=process` to the shebang line in `bin/jupyter-chatbook.raku`.

I'm not able to fully test either case at the moment, but I'm Feeling Confident™ :)

**Comment by antononcube** [comment]
After changing this code in "jupyter-chatbook.raku":

```
            "argv": [
                $exe,
                "--repl-mode=process",
```

to

```
            "argv": [
                "$exe",
                "--repl-mode=process",
```

I was able to start the Raku Chatbook kernel, but evaluation terminates with message about failing to connect / get a response.

**Comment by ab5tract** [comment]
Ok, I will look into this today -- with actual testing on my side :)

**Review by antononcube — APPROVED** [review]
New docker files.

**Pull request merged**
